name: nextjs-app
services:
  devcontainer:
    container_name: nextjs-devcontainer
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: devcontainer
    image: nextjs/code
    volumes:
      - '.:/var/www/html'
    networks:
      - nextjs
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  app:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: app
    image: nextjs/app
    ports:
      - '${APP_PORT:-3000}:3000'
      - '${DEBUG_PORT:-9229}:9229'
    environment:
      NODE_ENV: development
      DATABASE_URL: 'postgresql://${DB_USERNAME:-username}:${DB_PASSWORD:-password}@postgres:5432/${DB_DATABASE:-nextjs}'
    volumes:
      - .:/var/www/html
    depends_on:
      postgres:
        condition: service_healthy
      pnpm:
        condition: service_completed_successfully
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 5s
      timeout: 20s
      retries: 10
    restart: on-failure
    networks:
      - nextjs

  postgres:
    container_name: nextjs-postgres
    image: postgres:18-alpine
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE:-nextjs}'
      POSTGRES_USER: '${DB_USERNAME:-username}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
    volumes:
      - 'nextjs-postgres:/var/lib/postgresql'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME:-username}']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
    networks:
      - nextjs

  pnpm:
    container_name: nextjs-pnpm
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: pnpm
    image: nextjs/pnpm
    volumes:
      - .:/var/www/html
    networks:
      - nextjs

networks:
  nextjs:
    driver: bridge

volumes:
  nextjs-postgres:
    driver: local